### Endpoint de teste
GET http://localhost:3003/ping

###

POST http://localhost:3003/users/singup
Content-Type: application/json

{
    "name":"Patrick",
    "email":"Eu@example.com",
    "password":"123456"
}

###

POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email":"Eu@example.com",
    "password":"123456"
}

###

POST http://localhost:3003/posts/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZjNTAwMjk5LTUwMWUtNDVmNi04MGU0LWY1OTk1N2I0MTcyZCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjM4NzQ1MTgsImV4cCI6MTY2Mzk2MDkxOH0.01lyN9PnVlXo2tMz_LfR-PFNRoEnDLybM5HSdWeHM64

{
    "content":"Testezinho!"
}   

###

GET http://localhost:3003/posts//getAllPosts
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZjNTAwMjk5LTUwMWUtNDVmNi04MGU0LWY1OTk1N2I0MTcyZCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjM4NzQ1MTgsImV4cCI6MTY2Mzk2MDkxOH0.01lyN9PnVlXo2tMz_LfR-PFNRoEnDLybM5HSdWeHM64