### Endpoint de teste
GET http://localhost:3003/ping

### Endpoint de SingUp
POST http://localhost:3003/users/singup
Content-Type: application/json

{
    "name":"Patrick123",
    "email":"teste1342@example.com",
    "password":"123456"
}

### Endpoint de Login
POST http://localhost:3003/users/login
Content-Type: application/json

{
     "email":"fulano@gmail.com",
    "password":"qwerty00"
}

### Endpoint para criar shows
POST http://localhost:3003/shows/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjQ0NzcwODEsImV4cCI6MTY2NDU2MzQ4MX0.9r6SIxxnJyCeQY5VJkAWbaU4Bb53bF0ox0S7BwLw5S8

{
"band":"Teste",
"starts_at":"2022/12/07"
}

### Endpoint para pegar a lista de shows
GET http://localhost:3003/shows/getAllShows
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjQ0NzcwODEsImV4cCI6MTY2NDU2MzQ4MX0.9r6SIxxnJyCeQY5VJkAWbaU4Bb53bF0ox0S7BwLw5S8